config/routes.rb
Evergreen::Application.routes.draw do

  devise_for :users
devise_scope :user do
  authenticated :user do
    root :to => 'devise/sessions#new'
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new'
  end
end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root :to => 'users#index'
  end
  root :to => "users#index"
  devise_for :users
  resources :users do
    collection do
      get :show_suppliers
      get :show_members
    end
  end
  resources :upload_csvs
  resources :csvs

  resources :apisettings do
    collection do
      get :load_list
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/apisetting.rb
class Apisetting < ActiveRecord::Base
  attr_accessible :api_key, :list
end

app/models/csv.rb
class Csv < ActiveRecord::Base
  attr_accessible :csv
end

app/models/nouse.rb
class Nouse < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/upload_csv.rb
class UploadCsv < ActiveRecord::Base
  attr_accessible  :mclist_id, :date_added,:follow_up,:clicked_link_date,  :pdf_url,:message_sent,:last_message_name,:last_send_date,:remove_date,:remove_user
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :user_type
  
end

app/controllers/apisettings_controller.rb
class ApisettingsController < ApplicationController

  def new
    @apisetting = Apisetting.new
    if params.present?
    @listloaded = params[:listloaded]
     @api_key = params[:api_key]
    end

  end

  def load_list
    @api_key = params[:key]
    gb = Gibbon::API.new(@api_key)
    Gibbon::API.api_key = @api_key
    Gibbon::API.timeout = 15
    Gibbon::API.throws_exceptions = false

    # ------------load lists--------------

    @lists = Gibbon::API.lists.list
    @listloaded = []
    @lists['data'].each_with_index do |list, index|
      @listloaded[index] = {}
      @listloaded[index]["id"] = list["id"]
      @listloaded[index]["name"] = list["name"]
    end
    redirect_to new_apisetting_path({:listloaded => @listloaded, :api_key => @api_key})
  end


  def create
    @apisetting = Apisetting.first
    if @apisetting.present?
      @apisetting.update_attributes!(params[:apisetting])
      redirect_to root_url, :notice => "Successfully updated"
    else
      @apisetting = Apisetting.new(params[:apisetting])
      @apisetting.save!
      redirect_to root_url, :notice => "Successfully created"
   end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  #Custom route for devise, reroutes back to the homepage this is the root_path or root_url
  def after_sign_in_path_for(resource)
    #if current_user.sign_in_count == 1 && current_user.account.owner != current_user.id
    puts "888888888888888888888888888888888888888888888888"
    puts current_user.inspect
    if current_user.present?

    users_path
    else
      admin_root_path
    end
  end

  #Custom route for devise, after registration
  def after_sign_up_path_for(resource)
    users_path
  end

end

app/controllers/csvs_controller.rb
class CsvsController < ApplicationController

#   def new
#     @csv = Csv.new
#   end

#   def create
#     file = params[:file]
#     CSV.foreach(file.path, headers: true) do |row|
#       @upload_csv = UploadCsv.new
#       @upload_csv.save! row.to_hash
#     end
#    redirect_to upload_csvs_path
#   end

# end



# @exam.import_student(params[:file])
# def import_student(file)
#   @students = self.students
#   index = 0
#   CSV.foreach(file.path, headers: true) do |row|
#     @students[index].update_attributes! row.to_hash
#     index += 1
#   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/upload_csvs_controller.rb
class UploadCsvsController < ApplicationController
  def new
    @upload_csv = UploadCsv.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 #before_filter :authenticate_user!

  def index
    #authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end
  
  def show_members
    #authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.where(:user_type => 'Member')
  end

  def show_suppliers
    #authorize! :indsex, @user, :message => 'Not authorized as an administrator.'
    @users = User.where(:user_type => 'Supplier')
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def update
   # authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    
    user = User.find(params[:id])
    if user_signed_in? && current_user.user_type=="admin"
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Not authorized as an administrator."
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  
end

app/helpers/apisettings_helper.rb
module ApisettingsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/csvs_helper.rb
module CsvsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/upload_csvs_helper.rb
module UploadCsvsHelper
end

app/views/apisettings/_form.html.erb
<script type="text/javascript">
    $(document).ready(function () {
        $('#get-list').click(function (e) {
            e.preventDefault();
            var keyVal = $("#apisetting_api_key").val();
            var origin = window.location.origin;
            window.location.href = origin + '/apisettings/load_list?key=' + keyVal;
        });
    });
</script>

<%= form_for @apisetting, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="controls">
      <%= f.label :api_key %>
      <% if @api_key.present? %>
        <%= f.text_field :api_key, :value=>@api_key %>
      <% else %>
          <%= f.text_field :api_key %>
    <% end %>
        <%= link_to "getlist", "javascript:void(0)", :class=>"btn btn-mini btn-primary", :id=>"get-list" %>
    </div>

    <div class="control-group">

      <div class="controls">
        <% if @listloaded %>
            <label>Select List</label>
            <%= f.select :list, [['Select List', '']].concat(@listloaded.inject([]) {|arr, e| arr <<  [e["name"],e["id"]]}) %>
        <%end%>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit :submit, :class => 'btn btn-primary', :value => "Submit" %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  apisettings_path, :class => 'btn' %>
    </div>


<% end %>
<%= form_for @apisetting, :html => {:class => 'form-horizontal'} do |f| %>
  <h3><%= "Mandrill API" %></h3>
    <div class="controls">
      <%= f.label :api_key %>

      <%= f.text_field :api_key %>
      <%= link_to "getlist", "#", :class=>"btn btn-mini btn-primary" %>
    </div>


<% end %>

app/views/apisettings/edit.html.erb
<%- model_class = Apisetting -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apisettings/index.html.erb
<%- model_class = Apisetting -%>

app/views/apisettings/new.html.erb
<%- model_class = Apisetting -%>
<div class="page-header">
  <h3>API Settings</h3>
</div>
<%= render :partial => 'form' %>

app/views/apisettings/show.html.erb
<%- model_class = Apisetting -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:api_key) %>:</strong></dt>
  <dd><%= @apisetting.api_key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:list) %>:</strong></dt>
  <dd><%= @apisetting.list %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              apisettings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_apisetting_path(@apisetting), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              apisetting_path(@apisetting),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/csvs/_form.html.erb
<%= form_for @csv, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.file_field :csv %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                csvs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/csvs/edit.html.erb
<%- model_class = Csv -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/csvs/index.html.erb
<%- model_class = Csv -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:csv) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @csvs.each do |csv| %>
      <tr>
        <td><%= link_to csv.id, csv_path(csv) %></td>
        <td><%= csv.csv %></td>
        <td><%=l csv.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_csv_path(csv), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      csv_path(csv),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_csv_path,
            :class => 'btn btn-primary' %>

app/views/csvs/new.html.erb
<%- model_class = Csv -%>
<div class="page-header">
  <h3>Upload csv</h3>
</div>
<%= render :partial => 'form' %>

app/views/csvs/show.html.erb
<%- model_class = Csv -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:csv) %>:</strong></dt>
  <dd><%= @csv.csv %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              csvs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_csv_path(@csv), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              csv_path(@csv),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Evergreen", root_path, :class => 'brand' %>
<ul class="nav">

  <% if user_signed_in? && current_user.user_type=="admin" %>
      <li>
        <%= link_to 'Suppliers', show_suppliers_users_path %>
      </li>
      <li>
        <%= link_to 'Members', show_members_users_path %>
      </li>

  <% end %>
  <% if user_signed_in? %>
      <li>
        
      </li>
  <% end %>
  <% if user_signed_in? %>
      <% if current_user.user_type=="admin" %>
      <li class="offset3">
      <% else %>
          <li class="offset6">
        <% end %>
    <%= link_to 'Logout', destroy_user_session_path , method: :delete %>
    </li>
  <% else %>
    <li  class="offset7">
    <%= link_to 'Login', new_user_session_path, :class=>"pull-right" %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path, :class=>"pull-right" %>
    </li>
  <% end %>
  <%# if user_signed_in? && current_user.user_type=="admin" %>
      <!--<li>-->
        <%#= link_to 'Sign up', new_user_registration_path %>
      <!--</li>-->
  <%# end %>

</ul>



<%# if current_user.has_role? :admin %>
    <!--<li>-->
      <%#= link_to 'Admin', users_path %>
    <!--</li>-->
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails3 Bootstrap Devise Cancan" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top navbar-inverse" >
            <a class='btn btn-navbar' data-target='.nav-collapse' data-toggle='collapse'>
              <span class='icon-bar'></span>
              <span class='icon-bar'></span>
              <span class='icon-bar'></span>
            </a>

            <a class='brand' href='/'>
              <span class='icon-bar'></span>
              <span class='icon-bar'></span>
              <span class='icon-bar'></span>

              <img src='/favicon.ico'>
            </a>

      <nav class="navbar-inner" style="background-color: black">
        <div class="container" >
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/table.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails3 Bootstrap Devise Cancan" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/upload_csvs/_form.html.erb
<%= simple_form_for @upload_csv, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :mclist_id %>
  <%= f.input :date_added %>
  <%= f.input :follow_up %>
  <%= f.input :clicked_link_date %>
  <%= f.input :pdf_url %>
  <%= f.input :message_sent %>
  <%= f.input :last_message_name %>
  <%= f.input :last_send_date %>
  <%= f.input :remove_date %>
  <%= f.input :remove_user %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                upload_csvs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/upload_csvs/edit.html.erb
<%- model_class = UploadCsv -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/upload_csvs/index.html.erb
<%- model_class = UploadCsv -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:mclist_id) %></th>
      <th><%= model_class.human_attribute_name(:date_added) %></th>
      <th><%= model_class.human_attribute_name(:follow_up) %></th>
      <th><%= model_class.human_attribute_name(:clicked_link_date) %></th>
      <th><%= model_class.human_attribute_name(:pdf_url) %></th>
      <th><%= model_class.human_attribute_name(:message_sent) %></th>
      <th><%= model_class.human_attribute_name(:last_message_name) %></th>
      <th><%= model_class.human_attribute_name(:last_send_date) %></th>
      <th><%= model_class.human_attribute_name(:remove_date) %></th>
      <th><%= model_class.human_attribute_name(:remove_user) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @upload_csvs.each do |upload_csv| %>
      <tr>
        <td><%= link_to upload_csv.id, upload_csv_path(upload_csv) %></td>
        <td><%= upload_csv.mclist_id %></td>
        <td><%= upload_csv.date_added %></td>
        <td><%= upload_csv.follow_up %></td>
        <td><%= upload_csv.clicked_link_date %></td>
        <td><%= upload_csv.pdf_url %></td>
        <td><%= upload_csv.message_sent %></td>
        <td><%= upload_csv.last_message_name %></td>
        <td><%= upload_csv.last_send_date %></td>
        <td><%= upload_csv.remove_date %></td>
        <td><%= upload_csv.remove_user %></td>
        <td><%=l upload_csv.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_upload_csv_path(upload_csv), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      upload_csv_path(upload_csv),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_upload_csv_path,
            :class => 'btn btn-primary' %>

app/views/upload_csvs/new.html.erb
<%- model_class = UploadCsv -%>
<div class="page-header">
  <h3>Upload CSV</h3>
</div>
<%= render :partial => 'form' %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
  <h1 class = "text-center">Edit User</h1>
  <%= form_for @user , :html => { :multipart => :true, :method => 'put' }  do |f| %>
    <div class = "text-center">
      <div class="input-lg">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
    </div>
    <div class = "text-center">
      <div  data-style="btn-inverse" id = "type" >
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
    </div>
    <div class = "text-center">
      <div  data-style="btn-inverse" id = "status">
        <%= f.label :user_type %>
        <%= f.select :user_type, options_for_select(%w[Supplier Member], :html_options => {:class => "some-class"}  ) %>
      </div>
    </div>
    	<div class = "text-center">
      <div class="btn btn-default btn-lg" name "comit"><%= f.submit 'Edit User', :class => 'btn btn-danger' %></div>
  </div>
  <% end %>
  <div class="field" id = "sttatus">
  </div>

   

app/views/users/index.html.erb
<% if @users.present? %>
<h3>Users</h3>
<div class="span8"> 
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<% end %>

app/views/users/show_members.html.erb
<h3>Members</h3>
<% if @users.present? %>
<div class="span8"> 
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      
      
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
      <td><%= link_to("Edit user", edit_user_path(user), :data => { :confirm => "Are you sure?" }, :method => :get, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<% end %>

app/views/users/show_suppliers.html.erb
<h3>Suppliers</h3>
<% if @users.present? %>
<div class="span8"> 
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      
      
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
      <td><%= link_to("Edit user", edit_user_path(user), :data => { :confirm => "Are you sure?" }, :method => :get, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<% end %>